### ISSUE TITLE
Page reload deletes the TODO list!

### ISSUE THREAD

**Issue by trillionclues** [alexandrakononenko/NEW-ToDo-List#2]
Hi Alexandra,

Trust you're doing great.

## Description:
I found out when using your TODO app that the list gets wiped out on page reload. I don't know if you planned it this way but, it'd be super cool to see my list retained even after I mistakenly close the tab.

## Probable Solution
I was thinking a solution to this might be storing the entered key values in the localStorage. While I have knowledge of doing this using vanilla javascript, I wouldn't know if the same works for React as I'm still getting to grips with React.

Conclusion:
You have built really nice projects here and cannot wait to work with you on one someday :)

**Comment by AlexandraKon** [comment]
Hey Excel, 

Thanks for your comment and your advice! 

I have not yet connected localStorage to this project, but I hope in the near future I will fix it and the application will be improved. 

It will be nice to work with you on some project!

**Comment by trillionclues** [comment]
Alright, that'd be cool!

I started working with hooks and react-router. While I'm no way near good with these, I believe practicing with them will make me understand them better.

I recently did one with useState and useEffect hook, guess I will send a LinkedIn message when I have enough knowledge to work on an eCommerce application.
